"""Schemas package."""

from app.schemas.auth import (
    ApiTokenCreate,
    ApiTokenOut,
    ApiTokenOutWithToken,
    LoginRequest,
    Token,
    TokenRefresh,
    UserCreate,
    UserOut,
)
from app.schemas.finance import (
    AccountCreate,
    AccountOut,
    CashflowQueryParams,
    CashflowReportResponse,
    CategoryCreate,
    CategoryOut,
    PlannedPaymentCreate,
    PlannedPaymentOut,
    ProjectionExecutionSummary,
    ProjectionGenerationResult,
    PnLQueryParams,
    PnLReportResponse,
    ProjectedTransactionConfirmRequest,
    ProjectedTransactionConfirmResponse,
    ProjectedTransactionCreate,
    ProjectedTransactionOut,
    ProjectedTransactionUpdate,
    ReportCategoryTotal,
    ReportDateRange,
    ReportGroupBy,
    ReportTypeTotal,
    TransactionCreate,
    TransactionOut,
)
from app.schemas.parse_create import (
    ParseAndCreateResponse,
    ParsedResult,
    ParseErrorResponse,
    ParseRequest,
    TransactionCreateRequest,
)

__all__ = [
    # Auth
    "UserCreate",
    "UserOut",
    "LoginRequest",
    "Token",
    "TokenRefresh",
    "ApiTokenCreate",
    "ApiTokenOut",
    "ApiTokenOutWithToken",
    # Finance
    "AccountCreate",
    "AccountOut",
    "CategoryCreate",
    "CategoryOut",
    "PlannedPaymentCreate",
    "PlannedPaymentOut",
    "ProjectionExecutionSummary",
    "ProjectionGenerationResult",
    "ProjectedTransactionCreate",
    "ProjectedTransactionOut",
    "ProjectedTransactionUpdate",
    "ProjectedTransactionConfirmRequest",
    "ProjectedTransactionConfirmResponse",
    "TransactionCreate",
    "TransactionOut",
    # Reports
    "ReportDateRange",
    "ReportGroupBy",
    "PnLQueryParams",
    "CashflowQueryParams",
    "PnLReportResponse",
    "CashflowReportResponse",
    "ReportCategoryTotal",
    "ReportTypeTotal",
    # Parse-and-create
    "ParseRequest",
    "ParsedResult",
    "TransactionCreateRequest",
    "ParseAndCreateResponse",
    "ParseErrorResponse",
]
